### ISSUE TITLE
No flash with skylark-chip-flash-v4.0-201611240128+19942a1.vmflasher.ova

### ISSUE THREAD

**Issue by thomslik** [Othernet-Project/Skylark_beta_tracker#1]
No Go here with Ubuntu 16.10 and virtual box. I get is Waiting for CHIP in FEL mode and then Unable to find CHIP in FEL mode. lusb shows CHIP as: Bus 001 Device 009: ID 1f3a:efe8 Onda (unverified) V972 tablet in flashing mode

**Comment by syedkarim** [comment]
Does the host machine have hardware virtualization? If it does, are the
settings enabled in BIOS?
ᐧ

**Comment by abgoyal** [comment]
try under sudo:
```
# import ova to roots' virtualbox
sudo gnome-open _path_to_ova_ 
# start roots virtualbox
sudo virtualbox
```

**Comment by thomslik** [comment]
Sudo virtualbox and then importing the OVA into virtualbox worked.
