### ISSUE TITLE
USB0 network clash/feature request

### ISSUE THREAD

**Issue by shivalwolf** [Othernet-Project/Skylark_beta_tracker#5]
The USB0 interface uses 10.10.10.0/24 this is a common network range on some home routers (along with 192.168.0.0/24, 192.168.1.0/24, 10.0.0.0/24 

If setting the WIFI into client mode to join your network and your LAN is on 10.10.10.0/24 it will not work as USB0 has the lower network metric as it is a wired interface.

Afew suggestions for resolving this issue that may be a feature request.

1. Move USB0 onto a non standard ip range/smaller subnet such as something higher up the range such as 192.168.231.0/24 or 10.10.231.0/24 neither appear to be used as standard on home equipment i could find.

2. Allow for persistent changes by making the /etc/network/profiles.d on the /mnt/conf partition and also making the entire /etc/conf.d/ directory on the /mnt/conf partition instead of just the wireless folder that is inside /etc/conf.d. It could also be helpful if the entire /etc/ directory was on the /mnt/conf partition.

3. provide a UI feature to set the IP information on all interfaces including setting static IP information when joining a regular wifi network.

**Comment by abgoyal** [comment]
usb0 being a local link-only interface, and there being no "universally valid" solution to this, closing this as wontfix.
