### ISSUE TITLE
Wikipedia: Unable to move pane to the right

### ISSUE THREAD

**Issue by syedkarim** [Othernet-Project/Skylark_beta_tracker#7]
I can move the column (see scrot) to the left, but not back over to the right. 

![image](https://cloud.githubusercontent.com/assets/1186964/21595839/ff2566c8-d0f7-11e6-80c1-e28e61d1ef58.png)

**Comment by syedkarim** [comment]
Strange. It just snapped back to the right, after about 2 minutes.

**Comment by abgoyal** [comment]
does that when the app refreshes.
