### ISSUE TITLE
Tuner display not showing up-to-date status

### ISSUE THREAD

**Issue by kamotswind** [Othernet-Project/Skylark_beta_tracker#8]
I believe this is already reported on the forum, but I thought it would be a good idea to track here. The tuner status display does not show the most up-to-date status based on watching the root screen running demod_bin. It seems to be refreshing properly so I am guessing (without much research) the software running on the CHIP is not providing any update.

If this bug is still open and needs more information I'll be happy to run some diagnostics. It could be a browser cache issue? Also how do you re-enable web access logging? I do not see the log anymore after upgrading to Skylark.

**Comment by syedkarim** [comment]
Can you confirm this bug on Skylark v1.0?

**Comment by kamotswind** [comment]
This is resolved in Skylark v1.0 from file skylark-chip-flash-v4.2-1701041326+f85f1c1.vmflasher.ova
